version: '3.8'

services:
  security-dashboard:
    build: .
    container_name: security-analysis-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
